version: '3.7'
services:
  db:
    image: mysql:5.7
    command: --query_cache_type=0 --key_buffer_size=8 --innodb_buffer_pool_size=1M --query_cache_size=0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: revou
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
